USE DATABASE <<LZ>>;

--Schema
CREATE SCHEMA FILE;
CREATE SCHEMA SNOWFLAKE_SAMPLE_DB;

--File Formats
CREATE FILE FORMAT FILE.CSV_FILE_FORMAT
COMPRESSION = 'AUTO' FIELD_DELIMITER = ','
RECORD_DELIMITER = '\n' SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '\042' TRIM_SPACE = FALSE
ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE ESCAPE = 'NONE'
ESCAPE_UNENCLOSED_FIELD = 'NONE' DATE_FORMAT = 'AUTO'
TIMESTAMP_FORMAT = 'AUTO' NULL_IF = ('');

CREATE FILE FORMAT FILE.json_file_format
TYPE = 'JSON' COMPRESSION = 'AUTO' ENABLE_OCTAL = FALSE
ALLOW_DUPLICATE = FALSE STRIP_OUTER_ARRAY = TRUE
STRIP_NULL_VALUES = FALSE IGNORE_UTF8_ERRORS = FALSE;

CREATE FILE FORMAT FILE.avro_file_format
TYPE = 'AVRO' COMPRESSION = 'AUTO';

CREATE FILE FORMAT FILE.parquet_file_format
TYPE = 'PARQUET' COMPRESSION = 'AUTO' BINARY_AS_TEXT = TRUE;

CREATE FILE FORMAT SNOWFLAKE_SAMPLE_DB.CSV_FILE_FORMAT
COMPRESSION = 'AUTO' FIELD_DELIMITER = ','
RECORD_DELIMITER = '\n' SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '\042' TRIM_SPACE = FALSE
ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE ESCAPE = 'NONE'
ESCAPE_UNENCLOSED_FIELD = 'NONE' DATE_FORMAT = 'AUTO'
TIMESTAMP_FORMAT = 'AUTO' NULL_IF = ('');

--Stages
CREATE STAGE FILE.my_stage;
CREATE STAGE FILE.your_stage;
CREATE STAGE FILE.avro_parquet_stage;
CREATE STAGE SNOWFLAKE_SAMPLE_DB.sf_sample_stage;

--Tables
CREATE OR REPLACE TABLE FILE.TWCS_FULL
(TWEET_ID INTEGER,
AUTHOR_ID STRING,
INBOUND BOOLEAN,
CREATED_AT STRING,
TEXT STRING,
RESPONSE_TWEET_ID STRING,
IN_RESPONSE_TO_TWEET_ID STRING);

CREATE OR REPLACE TABLE FILE.TWEETS
(TWEET_ID STRING,
AIRLINE_SENTIMENT STRING,
AIRLINE_SENTIMENT_CONFIDENCE STRING,
NEGATIVEREASON STRING,
NEGATIVEREASON_CONFIDENCE STRING,
AIRLINE STRING,
AIRLINE_SENTIMENT_GOLD STRING,
NAME STRING,
NEGATIVEREASON_GOLD STRING,
RETWEET_COUNT STRING,
TEXT STRING,
TWEET_COORD STRING,
TWEET_CREATED STRING,
TWEET_LOCATION STRING,
USER_TIMEZONE STRING);

CREATE OR REPLACE TABLE FILE.PROFILE
(JSON_COLS VARIANT);

CREATE OR REPLACE TABLE FILE.TWEETSCHAMPIONS
(JSON_COLS VARIANT);

CREATE OR REPLACE TABLE FILE.AGENTS_PARQUET
(PARQUET_COLS VARIANT);

CREATE OR REPLACE TABLE FILE.STATES
(AVRO_COLS VARIANT);

CREATE OR REPLACE TABLE SNOWFLAKE_SAMPLE_DB.CUSTOMER
LIKE "SNOWFLAKE_SAMPLE"."TPCH_SF001"."CUSTOMER";

CREATE OR REPLACE TABLE SNOWFLAKE_SAMPLE_DB.LINEITEM
LIKE "SNOWFLAKE_SAMPLE"."TPCH_SF001"."LINEITEM";

CREATE OR REPLACE TABLE SNOWFLAKE_SAMPLE_DB.NATION
LIKE "SNOWFLAKE_SAMPLE"."TPCH_SF001"."NATION";

CREATE OR REPLACE TABLE SNOWFLAKE_SAMPLE_DB.ORDERS
LIKE "SNOWFLAKE_SAMPLE"."TPCH_SF001"."ORDERS";

CREATE OR REPLACE TABLE SNOWFLAKE_SAMPLE_DB.PART
LIKE "SNOWFLAKE_SAMPLE"."TPCH_SF001"."PART";

CREATE OR REPLACE TABLE SNOWFLAKE_SAMPLE_DB.PARTSUPP
LIKE "SNOWFLAKE_SAMPLE"."TPCH_SF001"."PARTSUPP";

CREATE OR REPLACE TABLE SNOWFLAKE_SAMPLE_DB.REGION
LIKE "SNOWFLAKE_SAMPLE"."TPCH_SF001"."REGION";

CREATE OR REPLACE TABLE SNOWFLAKE_SAMPLE_DB.SUPPLIER
LIKE "SNOWFLAKE_SAMPLE"."TPCH_SF001"."SUPPLIER";