name: Snowflake-CI

on:
  pull_request:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
            python-version: 3.7

      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v2.1.0
        with:
          path: python/requirements_snowflake_sql.txt
